config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: :task

  get    'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch  'tasks/:id',      to: 'tasks#update'

  delete 'tasks/:id',      to: 'tasks#destroy', as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_tasks, only: %i[index show]
  before_action :set_task, only: %i[edit update destroy]
  def index; end

  def new
    @task = Task.new # needed to instantiate the form_for
  end

  def create
    @task = Task.new(task_params)
    @task.save

    # no need for app/views/tasks/create.html.erb
    redirect_to task_path(@task)
  end

  def show
    @task = @tasks.find(params[:id])
  end

  def edit; end

  def update
    @task.update(task_params)

    # no need for app/views/tasks/update.html.erb
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy

    # no need for app/views/tasks/destroy.html.erb
    redirect_to root_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

  def set_tasks
    @tasks = Task.all
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <h1>My Task</h1>
   
    
  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_area :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h3> <%= link_to "Create", tasks_new_path %></h3>
<ul>
  <% @tasks.each do |task| %>
  <%= link_to task.title, task_path(task.id) %>

    <p><li><%= hidden_field_tag "checked[#{task.id}]", "false" %>
    <%= check_box_tag "checked[#{task.id}]","#{task.id}", task.completed %>
    <%= link_to "Delete",
            task_path(task.id),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
    </li></p>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_area :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task["name"] %></h1>


<ul>
  <li><h2>
  <%= @task["title"] %>
  </h2></li> 
  <li><p>
   <%= @task["details"] %>
 </li>
 <li>
 <%= check_box_tag "checked[##{@task.id}]","#{@task.id}{}", @task.completed %>
 </li>
</ul>

<%= link_to "Delete",
            task_path(@task),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
<%= link_to "Edit", edit_path(@task.id) %>
<%= link_to "Back", root_path %>